
baseURL = "https://uxdc.pages.cloud.statcan.ca/sdr-chart-js-v1"

languageCode = "en"

title = "Statistics Canada Daily News Letter Redesign Project"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

theme = "canada.ca"

defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 20
